name: Build 6.6-OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"
  schedule:
    - cron: 0 19 * * *
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 6.6.config
  DIY_P1_SH: 6.6-part1.sh
  DIY_P2_SH: 6.6-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 检查项目分支
        uses: actions/checkout@v4

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) || true
          sudo -E apt update
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
            git gperf haveged help2man intltool libelf-dev libfuse-dev libglib2.0-dev libmpc-dev libncurses5-dev \
            libpython3-dev libreadline-dev libssl-dev libtool llvm msmtp ninja-build p7zip-full patch pkgconf \
            python3 python3-setuptools rsync squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto \
            xxd zlib1g-dev
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: 下载固件源码
        working-directory: /workdir
        run: |
          if [ -d openwrt/.git ]; then
            cd openwrt
            git reset --hard
            git pull
          else
            git clone $REPO_URL -b $REPO_BRANCH openwrt
          fi
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: 清理旧的构建目录
        run: rm -rf openwrt/{staging_dir,build_dir,tmp}

      - name: 加载自定义设置
        run: |
          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
          chmod +x $DIY_P1_SH
          cd openwrt && $GITHUB_WORKSPACE/$DIY_P1_SH

      - name: 下载和安装插件
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 应用自定义配置
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt && $GITHUB_WORKSPACE/$DIY_P2_SH

      - name: SSH 连接管理
        uses: P3TERX/ssh2actions@v1.0.0
        if: github.event.inputs.ssh == 'true'
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: 下载安装包
        run: |
          cd openwrt
          make defconfig
          make download -j8
          find dl -size -1024c -delete

      - name: 获取内核版本
        run: |
          echo "KERNEL_VERSION_6_6=$(grep 'LINUX_VERSION-6.6' openwrt/include/kernel-6.6 | cut -d' ' -f3)" >> $GITHUB_ENV

      - name: 编译固件
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: 查看磁盘使用情况
        run: df -hT && free -m

      - name: 上传 bin 目录
        uses: actions/upload-artifact@v4
        if: env.UPLOAD_BIN_DIR == 'true'
        with:
          name: OpenWrt_bin${{ env.FILE_DATE }}
          path: openwrt/bin

      - name: 整理固件
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: 上传固件到 GitHub
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-6.6${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}

      - name: 创建 Release 标签
        run: echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV

      - name: 发布到 Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: OpenWrt 6.6${{ env.KERNEL_VERSION_6_6 }}-X86-64_${{ env.FILE_DATE }}
          tag_name: ${{ env.release_tag }}
          files: ${{ env.FIRMWARE }}/*

      - name: 清理旧的工作流运行
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3

      - name: 删除旧的 Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 30
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
